// <auto-generated />
using System;
using MessageBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessageBoard.Migrations
{
    [DbContext(typeof(MessageBoardContext))]
    [Migration("20210121184909_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MessageBoard.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GroupName");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            GroupName = "Baby Animals"
                        },
                        new
                        {
                            GroupId = 2,
                            GroupName = "Secret Missions"
                        },
                        new
                        {
                            GroupId = 3,
                            GroupName = "Phobias"
                        });
                });

            modelBuilder.Entity("MessageBoard.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GroupId");

                    b.Property<string>("MessageAuthor");

                    b.Property<DateTime>("MessageDate");

                    b.Property<string>("MessagePost");

                    b.HasKey("MessageId");

                    b.HasIndex("GroupId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            GroupId = 1,
                            MessageAuthor = "Jessie Finks",
                            MessageDate = new DateTime(2021, 1, 21, 10, 49, 8, 838, DateTimeKind.Local).AddTicks(2340),
                            MessagePost = "Kittens are my favorite baby animal"
                        },
                        new
                        {
                            MessageId = 2,
                            GroupId = 1,
                            MessageAuthor = "Arthur Aadvark",
                            MessageDate = new DateTime(2021, 1, 21, 10, 49, 8, 857, DateTimeKind.Local).AddTicks(8000),
                            MessagePost = "Puppies are my favorite baby animal"
                        },
                        new
                        {
                            MessageId = 3,
                            GroupId = 3,
                            MessageAuthor = "Not-a-podiatrist",
                            MessageDate = new DateTime(2021, 1, 21, 10, 49, 8, 857, DateTimeKind.Local).AddTicks(8040),
                            MessagePost = "I'm afraid of feet"
                        },
                        new
                        {
                            MessageId = 4,
                            GroupId = 2,
                            MessageAuthor = "Agent Anonymous",
                            MessageDate = new DateTime(2021, 1, 21, 10, 49, 8, 857, DateTimeKind.Local).AddTicks(8040),
                            MessagePost = "When the minute hand strikes a tadpole's tail past the high-noon hour, meet me at the phantom clocktower behind O'Henry's for your secret mission"
                        },
                        new
                        {
                            MessageId = 5,
                            GroupId = 3,
                            MessageAuthor = "FearOfClowns",
                            MessageDate = new DateTime(2021, 1, 21, 10, 49, 8, 857, DateTimeKind.Local).AddTicks(8040),
                            MessagePost = "Balloons are scary"
                        });
                });

            modelBuilder.Entity("MessageBoard.Models.Message", b =>
                {
                    b.HasOne("MessageBoard.Models.Group", "Group")
                        .WithMany("Messages")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
